package ci.prosumagpv.web.bean.util;

import java.util.ArrayList;
import java.util.List;

public class CountryUtil {
	
	
	private  CountryUtil() {
		
	}
	
	public static List<String>  getAllCountries(){
		ArrayList<String> listPays = new ArrayList<String>();
		listPays.add("Afrique Du Sud");
		listPays.add("Algérie");
		listPays.add("Angola");
		listPays.add("Bénin");
		listPays.add("Botswana");
		listPays.add("Burkina");
		listPays.add("Burundi");
		listPays.add("Cameroun");
		listPays.add("Cap-Vert");
		listPays.add("République Centre-Africaine");
		listPays.add("Comores");
		listPays.add("République Démocratique Du Congo");
		listPays.add("Congo");
		listPays.add("Cote d Ivoire");
		listPays.add("Djibouti");
		listPays.add("égypte");
		listPays.add("éthiopie");
		listPays.add("érythrée");
		listPays.add("Gabon");
		listPays.add("Gambie");
		listPays.add("Ghana");
		listPays.add("Guinée");
		listPays.add("Guinée-Bisseau");
		listPays.add("Guinée équatoriale");
		listPays.add("Kenya");
		listPays.add("Lesotho");
		listPays.add("Liberia");
		listPays.add("Libye");
		listPays.add("Madagascar");
		listPays.add("Malawi");
		listPays.add("Mali");
		listPays.add("Maroc");
		listPays.add("Maurice");
		listPays.add("Mauritanie");
		listPays.add("Mozambique");
		listPays.add("Namibie");
		listPays.add("Niger");
		listPays.add("Nigeria");
		listPays.add("Ouganda");
		listPays.add("Rwanda");
		listPays.add("Sao Tomé-et-Principe");
		listPays.add("Séngal");
		listPays.add("Seychelles");
		listPays.add("Sierra");
		listPays.add("Somalie");
		listPays.add("Soudan");
		listPays.add("Swaziland");
		listPays.add("Tanzanie");
		listPays.add("Tchad");
		listPays.add("Togo");
		listPays.add("Tunisie");
		listPays.add("Zambie");
		listPays.add("Zimbabwe");
		listPays.add("Antigua-et-Barbuda");
		listPays.add("Argentine");
		listPays.add("Bahamas");
		listPays.add("Barbade");
		listPays.add("Belize");
		listPays.add("Bolivie");
		listPays.add("Brésil");
		listPays.add("Canada");
		listPays.add("Chili");
		listPays.add("Colombie");
		listPays.add("Costa Rica");
		listPays.add("Cuba");
		listPays.add("République Dominicaine");
		listPays.add("Dominique");
		listPays.add("équateur");
		listPays.add("états Unis");
		listPays.add("Grenade");
		listPays.add("Guatemala");
		listPays.add("Guyana");
		listPays.add("Haéti");
		listPays.add("Honduras");
		listPays.add("Jamaéque");
		listPays.add("Mexique");
		listPays.add("Nicaragua");
		listPays.add("Panama");
		listPays.add("Paraguay");
		listPays.add("Pérou");
		listPays.add("Saint-Cristophe-et-Niévés");
		listPays.add("Sainte-Lucie");
		listPays.add("Saint-Vincent-et-les-Grenadines");
		listPays.add("Salvador");
		listPays.add("Suriname");
		listPays.add("Trinité-et-Tobago");
		listPays.add("Uruguay");
		listPays.add("Venezuela");
		listPays.add("Afghanistan");
		listPays.add("Arabie Saoudite");
		listPays.add("Arménie");
		listPays.add("Azerbaédjan");
		listPays.add("Bahreén");
		listPays.add("Bangladesh");
		listPays.add("Bhoutan");
		listPays.add("Birmanie");
		listPays.add("Brunéi");
		listPays.add("Cambodge");
		listPays.add("Chine");
		listPays.add("Corée Du Sud");
		listPays.add("Corée Du Nord");
		listPays.add("émirats Arabe Unis");
		listPays.add("Géorgie");
		listPays.add("Inde");
		listPays.add("Indonésie");
		listPays.add("Iraq");
		listPays.add("Iran");
		listPays.add("Israél");
		listPays.add("Japon");
		listPays.add("Jordanie");
		listPays.add("Kazakhstan");
		listPays.add("Kirghistan");
		listPays.add("Koweét");
		listPays.add("Laos");
		listPays.add("Liban");
		listPays.add("Malaisie");
		listPays.add("Maldives");
		listPays.add("Mongolie");
		listPays.add("Népal");
		listPays.add("Oman");
		listPays.add("Ouzbékistan");
		listPays.add("Pakistan");
		listPays.add("Philippines");
		listPays.add("Qatar");
		listPays.add("Singapour");
		listPays.add("Sri Lanka");
		listPays.add("Syrie");
		listPays.add("Tadjikistan");
		listPays.add("Taéwan");
		listPays.add("Thaélande");
		listPays.add("Timor oriental");
		listPays.add("Turkménistan");
		listPays.add("Turquie");
		listPays.add("Viét Nam");
		listPays.add("Yemen");
		listPays.add("Allemagne");
		listPays.add("Albanie");
		listPays.add("Andorre");
		listPays.add("Autriche");
		listPays.add("Biélorussie");
		listPays.add("Belgique");
		listPays.add("Bosnie-Herzégovine");
		listPays.add("Bulgarie");
		listPays.add("Croatie");
		listPays.add("Danemark");
		listPays.add("Espagne");
		listPays.add("Estonie");
		listPays.add("Finlande");
		listPays.add("France");
		listPays.add("Gréce");
		listPays.add("Hongrie");
		listPays.add("Irlande");
		listPays.add("Islande");
		listPays.add("Italie");
		listPays.add("Lettonie");
		listPays.add("Liechtenstein");
		listPays.add("Lituanie");
		listPays.add("Luxembourg");
		listPays.add("Ex-République Yougoslave de Macédoine");
		listPays.add("Malte");
		listPays.add("Moldavie");
		listPays.add("Monaco");
		listPays.add("Norvége");
		listPays.add("Pays-Bas");
		listPays.add("Pologne");
		listPays.add("Portugal");
		listPays.add("Roumanie");
		listPays.add("Royaume-Uni");
		listPays.add("Russie");
		listPays.add("Saint-Marin");
		listPays.add("Serbie-et-Monténégro");
		listPays.add("Slovaquie");
		listPays.add("Slovénie");
		listPays.add("Suéde");
		listPays.add("Suisse");
		listPays.add("République Tchéque");
		listPays.add("Ukraine");
		listPays.add("Vatican");
		listPays.add("Australie");
		listPays.add("Fidji");
		listPays.add("Kiribati");
		listPays.add("Marshall");
		listPays.add("Micronésie");
		listPays.add("Nauru");
		listPays.add("Nouvelle-Zélande");
		listPays.add("Palaos");
		listPays.add("Papouasie-Nouvelle-Guinée");
		listPays.add("Salomon");
		listPays.add("Samoa");
		listPays.add("Tonga");
		listPays.add("Tuvalu");
		listPays.add("Vanuatu");
		
		return listPays;
	}

}
